title: Blog - Leach Chen
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
#baseurl: "/adam-blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings add your name
author: Leach Chen 

author-pic: leach-face.jpg
about-author: I will add description latter.                                                                    

# Contact links
website: # Add your website, do not add http://
linkedin: # Add your Linkedin handle
twitter: # Add your Twitter handle
facebook: # Add your Facebook handle
instagram: # Add your Instagram handle
pinterest: # Add your Pinterest handle

email: leach.chen@gmail.com
phone: 00000000
github: https://github.com/leach-chen
jianshu: https://www.jianshu.com/users/5cc3aae52717/timeline
juejin: https://juejin.im/user/581b4a3e2e958a0054d47b57/collections
csdn: http://blog.csdn.net/chenliqiang12345678

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: leach-chen 
# Add your discus identifier

#intensedebate
intensedebate_identifier: 1ce8d80a5f6d373a46f4ceaf3dff8859

# Tracker Google Analytics
google-analysis: UA-113644888-1
baidu-analysis: 56385150d223d3a72bebe8a0d4a94e19

#youyan
youyan-id: 2157296

# Paginate
paginate: 18
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]


links:
  - name:         Home
    url:          /
    external:     false
  - name:         About
    url:          /about
    external:     false
    
#添加分类步骤：
#1：在_config.yml links1及blog_中添加对应内容
#2：在_includes里面headr.html中添加对应内容
#3：在根目录blog文件中创建对应内容

    
links1:
  - name:         最近
    url:          /
    type:         recent
    external:     false
  - name:         随笔
    url:          /blog/essays
    type:         essays
    external:     false
  - name:         Jekyll
    url:          /blog/jekyll
    type:         jekyll
    external:     false
  - name:         Android原创
    url:          /blog/androidoriginal
    type:         androidoriginal
    external:     false    
    
blog_1:    recent
blog_2:    essays   
blog_3:    jekyll   
blog_4:    androidoriginal   
blog_5:       
blog_6:       
blog_7:       
blog_8:       
blog_9:       
blog_10:      
blog_11:      
blog_12:      
blog_13:      
blog_14:      
blog_15:       
blog_16:           
    
    
#permalink: /:year/:month/:day/:title.html    
